print('              TECNOLÓGICO NACIONAL DE MÉXICO')
print('')
print('             INSTITUTO TECNOLÓGICO DE TIJUANA')
print('')
print('          DEPARTAMENTO DE SISTEMAS Y COMPUTACIÓN')
print('')
print('            SEMESTRE: AGOSTO - DICIEMBRE 2022')
print('')
print('          CARRERA: ING. SISTEMAS COMPUTACIONALES')
print('')
print('              MATERIA: LENGUAJE DE INTERFAZ')
print('')
print('                TITULO: PORTADA EN PYTHON')
print('')
print('        NOMBRE DEL ALUMNO: GUILLEN MARTINEZ ANTHONY')
print('')
print('          NÚMERO DE CONTROL DEL ALUMNO: 20210575')
print('')
print('                        UNIDAD: 2')
print('')
print('          NOMBRE DEL DOCENTE: RODRIGO CAÑEZ VALLE')
print('')
print('                        20/09/2022')
print('')